language: node_js
node_js:
  - 0.8
before_script:
  - wget https://github.com/n1k0/casperjs/archive/1.0.2.tar.gz -O casper.tar.gz
  - tar -xvf casper.tar.gz
  - export PATH=$PATH:$PWD/casperjs-1.0.2/bin/
script: make test-casper
notifications:
  irc: "irc.freenode.org#mootools-dev"
